openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Users API'
  description: API для пользователей по курсу Архитектура программных систем
servers:
  - url: http://localhost:8080
    description: Example server
paths:
  /search:
    get:
      summary: Поиск пользователей по маске имени и фамилии
      parameters:
      - name: first_name
        description: Имя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /search_by_login:
    get:
      summary: Поиск пользователей по  логину.
      parameters:
      - name: login
        description: Логин
        in: query
        required: true
        schema:
          type: string      
      responses:
        '200':
          description: The users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth:
    get:
      summary: Проверка аутентификации
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not authentication
          content:
            application/json:
              schema:
                type: string
  /user:
    get:
      summary: Чтение информации о пользователе
      parameters:
      - name: id
        description: Уникальный идентификатор пользователя
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового пользователя
      parameters:
      - name: first_name
        description: Имя пользователя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия пользователя
        in: query
        required: true
        schema:
          type: string
      - name: email
        description: email пользователя
        in: query
        required: true
        schema:
          type: string
      - name: title
        description: Форма обращение к пользователя 
        in: query
        required: true
        schema:
          type: string
      - name: login
        description: login пользователя
        in: query
        required: true
        schema:
          type: string
      - name: password
        description: пароль пользователя
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /message:
    get:
      summary: Read a messages
      parameters:
      - name: id_from
        description: Уникальный идентификатор автора отправителя сообщений
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      - name: id_to
        description: Уникальный идентификатор автора получателя сообщений
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: Сообщения между авторами
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messages'
        404:
          description: No author found for the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messages'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Send message
      parameters:
      - name: id_from
        description: id автора - отправителя сообщения
        in: query
        required: true
        schema:
          type: string
      - name: id_to
        description: id автора - получателя сообщения
        in: query
        required: true
        schema:
          type: string
      - name: message
        description: сообщение
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного сообщения
          content:
            application/json:
              schema:
                type: integer
        404:
          description: No author found for the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /wall:
        post:
            summary: Добавление записи на стену пользователя
            parameters:
                - name: post_title
                  in: query
                  description: Заголовок записи
                  required: true
                  schema:
                      type: string
                - name: post_text
                  in: query
                  description: Содержание записи
                  required: true
                  schema:
                      type: string                      
            responses:
                "200":
                    description: Ид записи
                    content:
                        application/json:
                         schema:
                          type: integer            
                404:
                    description: Ошибка записи на стену
                    content:
                        application/json:
                         schema:
                            $ref: '#/components/schemas/Error'
                500:
                    description: Неожиданная ошибка
                    content:
                        application/json:
                         schema:
                            $ref: '#/components/schemas/Error'
        get:
            summary: Получение списка записей на стене пользователя
            parameters:
                - name: user_id
                  in: query
                  description: Идентификатор стены(пользователя)
                  required: true
                  schema:
                      type: integer
            responses:
                '200':
                    description: Список записей успешно получен
                    content:
                     application/json:
                      schema:
                        $ref: '#/components/schemas/wall'   
                404:
                    description: Ошибка получения стены
                    content:
                        application/json:
                         schema:
                            $ref: '#/components/schemas/Error'
                500:
                    description: Неожиданная ошибка
                    content:
                        application/json:
                         schema:
                            $ref: '#/components/schemas/Error'   

components:
  schemas:
    user_id:
      description: Уникальный идентификатор пользователя
      type: integer
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    user:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - title
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        title:
          type: string
        login:
          type: string
        password:
          type: string
    messages:
      type: array
      items:
        $ref: '#/components/schemas/message'
    message:
      type: object
      properties:
        id:
          type: string
        id_from:
          type: string
        id_to:
          type: string
        message:
          type: string

    post_id:
          type: integer
          description: Уникальный идентификатор стены.        
    walls:
          type: array
          items:
              $ref: "#/components/schemas/wall"
    wall:
          type: object
          required:
              - id
              - user_id
              - post_text
          properties:
             id:
                $ref: '#/components/schemas/post_id'   
             user_id:
                 type: integer
             post_text:
                 type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []